name: "Build and Test"
description: "Run build and test steps for frontend project"
inputs:
  node_version:
    description: "Node.js version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: cloudops-one/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
