jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: cloudops-one/checkout@v4   # Your fork

      - name: Use Node.js ${{ inputs.node_version }}
        uses: cloudops-one/setup-node@v4  # Fork setup-node too if needed
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
