name: "Build and Test"
description: "Run build and test steps for frontend project"
inputs:
  node_version:
    description: "Node.js version"
    required: true
runs:
  using: "composite"
 steps:
  - name: Checkout code
    uses: cloudops-one/actions@v4       # For your fork of checkout
  - name: Setup Node.js
    uses: cloudops-one/setup-node@v4    # For your fork of setup-node
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Test
      run: npm test
      shell: bash
