name: CI/CD Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      docker_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "environment=live" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
          fi

      - name: Determine docker tag
        id: tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "tag=stage" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            echo "tag=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
          fi

  validate-branch:
    needs: determine-environment
    runs-on: ubuntu-latest
    outputs:
      branch_valid: ${{ steps.validation.outputs.valid }}
    steps:
      - name: Validate branch name
        id: validation
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          BRANCH_REGEX="^(feat|fix|chore|test|docs|refactor|ci|style|perf|build)/[0-9]{1,5}_[a-z0-9]+(-[a-z0-9]+)*$"

          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "valid=true" >> $GITHUB_OUTPUT
              echo "Tag $TAG_NAME is valid for live deployment"
            else
              echo "valid=false" >> $GITHUB_OUTPUT
              echo "Invalid tag format. Expected: v1.0.0"
              exit 1
            fi
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "Main branch is valid for stage deployment"
          elif [[ "$BRANCH_NAME" =~ $BRANCH_REGEX ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "Feature branch $BRANCH_NAME is valid for preview deployment"
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "Branch name does not match required pattern"
            exit 1
          fi

  build-and-test:
    needs: [determine-environment, validate-branch]
    if: needs.validate-branch.outputs.branch_valid == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: cloudops-one/checkout@v4
        
      - name: Build and test
        uses: cloudops-one/devops-ci/.github/actions/build-and-test@main
        with:
          project_type: 'react'
          node_version: '18'
          java_version: '11'
          build_tool: 'maven'
          sonarqube_token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube_url: ${{ secrets.SONARQUBE_URL }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Security scanning
        uses: cloudops-one/devops-ci/.github/actions/security-scan@main
        with:
          project_type: 'react'
          snyk_token: ${{ secrets.SNYK_TOKEN }}

  docker-build-push:
    needs: [determine-environment, build-and-test, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: cloudops-one/devops-ci/.github/actions/docker-operations@main
        with:
          operation: "build-push"
          harbor_registry: ${{ secrets.HARBOR_REGISTRY }}
          harbor_username: ${{ secrets.HARBOR_USERNAME }}
          harbor_password: ${{ secrets.HARBOR_PASSWORD }}
          project_name: 'portal-irai-yoga'
          component: 'web-app'
          docker_tag: ${{ needs.determine-environment.outputs.docker_tag }}

  deploy:
    needs: [determine-environment, docker-build-push]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - name: Setup environment
        uses: cloudops-one/devops-ci/.github/actions/setup-environment@main
        with:
          environment: ${{ needs.determine-environment.outputs.environment }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Kubernetes
        uses: cloudops-one/devops-ci/.github/actions/k8s-deploy@main
        with:
          environment: ${{ needs.determine-environment.outputs.environment }}
          project_name: 'portal-irai-yoga'
          component: 'web-app'
          docker_tag: ${{ needs.determine-environment.outputs.docker_tag }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          domain_config: ${{ vars.DOMAIN_CONFIG }}
          deploy_supporting_services: false

      - name: Determine webhook URL
        id: webhook
        run: |
          if [ "${{ needs.determine-environment.outputs.environment }}" = "preview" ]; then
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_PREVIEW }}" >> $GITHUB_OUTPUT
          elif [ "${{ needs.determine-environment.outputs.environment }}" = "stage" ]; then
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_STAGE }}" >> $GITHUB_OUTPUT
          else
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_LIVE }}" >> $GITHUB_OUTPUT
          fi

      - name: Notify deployment
        uses: cloudops-one/devops-ci/.github/actions/notify@main
        with:
          webhook_url: ${{ steps.webhook.outputs.webhook_url }}
          message: "✅ Deployment successful to ${{ needs.determine-environment.outputs.environment }}"
          environment: ${{ needs.determine-environment.outputs.environment }}
