name: CI/CD Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "environment=live" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
          fi

  call-shared-pipeline:
    needs: determine-environment
    uses: ./.github/workflows/main.yml
    with:
      project_type: 'java-spring'  # Change to 'react' for React projects
      environment: ${{ needs.determine-environment.outputs.environment }}
      project_name: 'irai-yoga-v1'  # Update with your project name
      component: 'server'  # Change to 'portal', 'frontend', etc.
      domain_config: |
        {
          "preview_domain": "irai.yoga",
          "stage_domain": "irai.yoga",
          "live_domain": "irai.yoga"
        }
      java_version: '17'
      build_tool: 'gradle'
      node_version: '18'
    secrets: inherit
