name: CI/CD Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches: ['**']
    tags: ['v*', '*.*.*']  # Updated: now accepts both v1.0.0 and 1.0.0 formats
  pull_request:
    branches: [main]

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      docker_tag: ${{ steps.tag.outputs.docker_tag }}
      branch_valid: ${{ steps.validation.outputs.valid }}
      domain: ${{ steps.domain.outputs.domain }}
    steps:
      - name: Determine environment and tag
        id: env
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "environment=live" >> $GITHUB_OUTPUT
            TAG="${GITHUB_REF#refs/tags/}"
            echo "docker_tag=$TAG" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
            echo "docker_tag=stage" >> $GITHUB_OUTPUT
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            echo "docker_tag=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
          fi
      - name: Determine domain
        id: domain
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "domain=live-domain-config" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "domain=stage-domain-config" >> $GITHUB_OUTPUT
          else
            echo "domain=preview-domain-config" >> $GITHUB_OUTPUT
          fi
      - name: Validate branch name
        id: validation
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          BRANCH_REGEX="^(feat|fix|chore|test|docs|refactor|ci|style|perf|build)/[0-9]{1,5}_[a-z0-9]+(-[a-z0-9]+)*$"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Updated regex: accepts both v1.0.0 and 1.0.0 formats
            if [[ "$TAG_NAME" =~ ^(v)?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "valid=true" >> $GITHUB_OUTPUT
              echo "Tag $TAG_NAME is valid for live deployment"
            else
              echo "valid=false" >> $GITHUB_OUTPUT
              echo "Invalid tag format. Expected: v1.0.0 or 1.0.0"
              exit 1
            fi
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "Main branch is valid for stage deployment"
          elif [[ "$BRANCH_NAME" =~ $BRANCH_REGEX ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "Feature branch $BRANCH_NAME is valid for preview deployment"
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "Branch name does not match required pattern"
            exit 1
          fi

  react-build:
    needs: validate-branch
    if: needs.validate-branch.outputs.branch_valid == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: cloudops-one/checkout@v4
        
      - name: Setup Node.js 20 (without cache)
        uses: cloudops-one/setup-node@v1
        with:
          node-version: '20'
          # Remove cache parameter completely to avoid lockfile errors
          
      - name: Skip husky installation (CI environment)
        run: |
          # Skip husky installation in CI environment by removing prepare script
          npm pkg delete scripts.prepare 2>/dev/null || echo "No prepare script to remove"
          npm pkg delete scripts.postinstall 2>/dev/null || echo "No postinstall script to remove"
          
      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "Generating package-lock.json..."
            npm install --package-lock-only --no-audit --no-fund
          else
            echo "package-lock.json already exists"
          fi
          
      - name: Install dependencies
        run: npm install --no-audit --no-fund --ignore-scripts
        
      - name: Build project
        run: npm run build
        env:
          CI: false

  docker-build-push:
    needs: [validate-branch, react-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: cloudops-one/checkout@v4
      
      - name: Build and push Docker image
        uses: cloudops-one/devops-ci/.github/actions/docker-operations@main
        with:
          harbor-registry: ${{ secrets.HARBOR_REGISTRY }}
          harbor-username: ${{ secrets.HARBOR_USERNAME }}
          harbor-password: ${{ secrets.HARBOR_PASSWORD }}
          project-name: 'portal-irai-yoga'
          component: 'admin'
          docker-tag: ${{ needs.validate-branch.outputs.docker_tag }}

  deploy:
    needs: [validate-branch, docker-build-push]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.validate-branch.outputs.environment }}
    steps:
      - name: Setup environment
        uses: cloudops-one/devops-ci/.github/actions/setup-environment@main
        with:
          environment: ${{ needs.validate-branch.outputs.environment }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Kubernetes
        uses: cloudops-one/devops-ci/.github/actions/k8s-deploy@main
        with:
          environment: ${{ needs.validate-branch.outputs.environment }}
          project-name: 'portal-irai-yoga'
          component: 'admin'
          docker-tag: ${{ needs.validate-branch.outputs.docker_tag }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          domain-config: ${{ needs.validate-branch.outputs.domain }}
          deploy-supporting-services: false

      - name: Determine webhook URL
        id: webhook
        run: |
          if [ "${{ needs.validate-branch.outputs.environment }}" = "preview" ]; then
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_PREVIEW }}" >> $GITHUB_OUTPUT
          elif [ "${{ needs.validate-branch.outputs.environment }}" = "stage" ]; then
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_STAGE }}" >> $GITHUB_OUTPUT
          else
            echo "webhook_url=${{ secrets.ZOHO_CLIQ_WEBHOOK_LIVE }}" >> $GITHUB_OUTPUT
          fi
      - name: Notify deployment
        uses: cloudops-one/devops-ci/.github/actions/notify@main
        with:
          webhook-url: ${{ steps.webhook.outputs.webhook_url }}
          message: "✅ Deployment successful to ${{ needs.validate-branch.outputs.environment }}"
          environment: ${{ needs.validate-branch.outputs.environment }}
