on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string
      environment:
        required: true
        type: string
      project_name:
        required: true
        type: string
      component:
        required: true
        type: string
      domain_config:
        required: true
        type: string
      java_version:
        required: true
        type: string
      build_tool:
        required: true
        type: string
      node_version:
        required: true
        type: string
    secrets:
      inherit: true

name: CI/CD Pipeline

permissions:
  actions: read
  contents: read

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "environment=live" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
          fi

  # other jobs here, but DO NOT call this workflow using `uses:` inside itself!
